config/routes.rb
EsimerkkiApp::Application.routes.draw do
  resources :machine_cover_image_names

  resources :machine_cover_image_uids

  resources :caravan_cover_image_names

  resources :caravan_cover_image_uids

  resources :moto_cover_image_names

  resources :moto_cover_image_uids

  resources :car_cover_image_names

  resources :car_cover_image_uids

  resources :boat_cover_image_names

  resources :boat_cover_image_uids

  resources :cover_image_names

  resources :cover_image_uids

  resources :boat_user_emails

  resources :boat_user_phones

  resources :boat_user_names

  resources :machine_color_types

  resources :machine_town_types

  resources :machine_user_emails

  resources :machine_user_phones

  resources :machine_user_names

  resources :caravan_town_types

  resources :caravan_user_emails

  resources :caravan_user_phones

  resources :caravan_user_names

  resources :caravan_total_owners

  resources :moto_town_types

  resources :moto_user_emails

  resources :moto_user_phones

  resources :moto_user_names

  resources :moto_engine_types

  resources :moto_prices

  resources :moto_registration_numbers

  resources :moto_models

  resources :moto_makes

  resources :sub_vehicles

  resources :vehicles

  resources :car_user_emails

  resources :car_user_phones

  resources :car_user_names

  resources :car_town_types

  resources :car_domicile_types

  resources :car_weights

  resources :car_accelerations

  resources :car_top_speeds

  resources :car_emissions

  resources :car_powers

  resources :car_gearbox_types

  resources :car_fuel_types

  resources :car_drive_types

  resources :car_engine_sizes

  resources :car_mileages

  resources :car_total_owners

  resources :car_informations

  resources :car_prices

  resources :car_color_types

  resources :car_colors

  resources :car_year_models

  resources :car_sub_types

  resources :car_model_sections

  resources :car_make_sections

  resources :car_types

  resources :boat_sub_types

  resources :boat_town_type_sections

  resources :boat_domicile_types

  resources :boat_makes

  resources :boat_sub_type_sections

  resources :boats

  resources :boat_domicile_type_sections

  resources :boat_town_types

  resources :boat_storage_equipments

  resources :boat_total_owners

  resources :boat_notes

  resources :boat_engine_fuel_types

  resources :boat_engine_year_models

  resources :boat_engine_makes

  resources :boat_draughts

  resources :boat_weights

  resources :boat_widths

  resources :boat_heights

  resources :boat_lengths

  resources :boat_body_materials

  resources :boat_asking_prices

  resources :boat_year_models

  resources :boat_subtype_sections

  resources :pictures

  resources :caravans

  resources :countries

  resources :focusing_sections

  resources :industries

  resources :machine_posts

  resources :machine_town_type_sections

  resources :machine_domicile_types

  resources :machine_total_owners

  resources :machine_informations

  resources :machine_drive_types

  resources :machine_fuel_types

  resources :machine_color_type_sections

  resources :machine_colors

  resources :machine_mileages

  resources :machine_engine_sizes

  resources :machine_year_models

  resources :machine_gross_weights

  resources :machine_prices

  resources :machine_engine_models

  resources :machine_models

  resources :machine_make_sections

  resources :machine_sub_type_sections

  resources :machine_category_sections

  resources :machine_types

  resources :caravan_posts

  resources :caravan_town_type_sections

  resources :caravan_domicile_types

  resources :caravan_mileages

  resources :caravan_informations

  resources :caravan_gross_weights

  resources :caravan_dead_weights

  resources :caravan_lenghts

  resources :total_owners

  resources :caravan_asking_prices

  resources :caravan_year_models

  resources :caravan_model_sections

  resources :caravan_make_sections

  resources :caravan_types

  resources :moto_posts

  resources :moto_town_type_sections

  resources :moto_domicile_types

  resources :moto_gearbox_types

  resources :moto_fuel_types

  resources :moto_drive_types

  resources :moto_mileages

  resources :moto_informations

  resources :moto_engine_sizes

  resources :engine_types

  resources :moto_color_types

  resources :moto_colors

  resources :moto_year_models

  resources :prices

  resources :registration_numbers

  resources :moto_model_sections

  resources :moto_make_sections

  resources :type_sections

  resources :vehicle_classes

  resources :boats_domicile_type_sections

  resources :boat_posts

  resources :domicile_type_sections

  resources :boats_position_town_types

  resources :storage_equipments

  resources :notes

  resources :draughts

  resources :weights

  resources :widths

  resources :heights

  resources :lengths

  resources :boat_colors

  resources :body_materials

  resources :asking_prices

  resources :year_models

  resources :boat_models

  resources :boat_make_sections

  resources :subtype_sections

  resources :boat_types

  resources :car_posts

  resources :town_types

  resources :domicile_types

  resources :gearbox_types

  resources :fuel_types

  resources :drive_types

  resources :engine_sizes

  resources :color_types

  resources :colors

  resources :model_sections

  resources :make_sections

  resources :windows

  resources :sub_cars

  resources :cars
  resources :sub_types
  resources :types

  resources :menus

  
 
  resources :ads

  resources :ilmoitus

  resources :galleries

  resources :sub_sections

  resources :sections

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  match '/sub_types/for_typeid/:id' => 'sub_types#for_typeid'

 get "sessions/new"

  resources :posts

  get "pages/usage"

  get "pages/post"

  get "pages/dogs"

  get "pages/images"
   

  resources :users
 
   match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
   match '/search',    :to => 'pages#search'

  match '/usage',    :to => 'pages#usage'
  match '/post',    :to => 'pages#post'
 

match '/focusing_sections/for_industryid/:id' => 'focusing_sections#for_industryid'
 
   match '/make_sections/for_typeid/:id' => 'make_sections#for_typeid'
   match '/model_sections/for_make_sectionid/:id' => 'model_sections#for_make_se   ctionid'
   match '/caravan_make_sections/for_caravantypeid/:id' => 'caravan_make_sections  #for_caravantypeid'

   match '/sub_sections/for_sectionid/:id' => 'sub_sections#for_sectionid'
   match '/caravan_make_sections/for_caravantypeid/:id' => 'caravan_make_sections#for_caravantypeid'
    match '/car_make_sections/for_cartypeid/:id' => 'car_make_sections#for_cartypeid'

 match '/machine_category_sections/for_machinetypeid/:id' => 'machine_category_sections#for_machinetypenid'
  match '/sub_vehicles/for_vehicleid/:id' => 'sub_vehicles#for_vehicleid'

 
root :to => 'pages#home'

 get "pages/home"

  get "pages/contact"

  get "pages/about"

  resources :microposts

  resources :users

  

end

app/models/boat_post.rb
class BoatPost < ActiveRecord::Base
image_accessor :boat_cover_image
 belongs_to :boat_type
belongs_to :boat_body_material

 belongs_to :boat_make
 belongs_to :boat_sub_type
  belongs_to :boat_color
 belongs_to :boat_engine_make
 belongs_to :boat_engine_fuel_type
 belongs_to :boat_domicile_type
 belongs_to :boat_town_type


 validates_presence_of :boat_type_id, :boat_body_material_id, :boat_make_id, :boat_sub_type_id, :boat_color_id, :boat_engine_make_id, :boat_engine_fuel_type_id, 
:boat_domicile_type_id, :boat_town_type_id

def self.search(search)
  if search
    find(:all, :conditions => ['boat_model LIKE ?', "%#{search}%"])
  else
    find(:all)
  end
end

end

app/controllers/boat_posts_controller.rb
class BoatPostsController < ApplicationController
  # GET /boat_posts
  # GET /boat_posts.xml
  def index
    @boat_posts = BoatPost.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @boat_posts }
@boat_posts = BoatPost.search(params[:search])
    end
  end

  # GET /boat_posts/1
  # GET /boat_posts/1.xml
  def show
    @boat_post = BoatPost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @boat_post }
    end
  end

  # GET /boat_posts/new
  # GET /boat_posts/new.xml
  def new
    @boat_post = BoatPost.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @boat_post }
    end
  end

  # GET /boat_posts/1/edit
  def edit
    @boat_post = BoatPost.find(params[:id])
  end

  # POST /boat_posts
  # POST /boat_posts.xml
  def create
    @boat_post = BoatPost.new(params[:boat_post])

    respond_to do |format|
      if @boat_post.save
        format.html { redirect_to(@boat_post, :notice => 'Boat post was successfully created.') }
        format.xml  { render :xml => @boat_post, :status => :created, :location => @boat_post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @boat_post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /boat_posts/1
  # PUT /boat_posts/1.xml
  def update
    @boat_post = BoatPost.find(params[:id])

    respond_to do |format|
      if @boat_post.update_attributes(params[:boat_post])
        format.html { redirect_to(@boat_post, :notice => 'Boat post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @boat_post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /boat_posts/1
  # DELETE /boat_posts/1.xml
  def destroy
    @boat_post = BoatPost.find(params[:id])
    @boat_post.destroy

    respond_to do |format|
      format.html { redirect_to(boat_posts_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/boat_posts_helper.rb
module BoatPostsHelper
end

app/views/boat_posts/_form.html.erb
<%= form_for(@boat_post) do |f| %>
  <% if @boat_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@boat_post.errors.count, "error") %> prohibited this boat_post from being saved:</h2>

      <ul>
      <% @boat_post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div style="overflow:auto; height:900px;width:650px;">

  <p>
    <%= f.label :Tyyppi %><br />
   <%=  collection_select(:boat_post, :boat_type_id, BoatType.all, :id, :name , options ={:prompt => "Valitse tyyppi"} ) %>
    </p>
   <p>
    <%= f.label :Merkki %><br />
   <%= collection_select(:boat_post, :boat_make_id, BoatMake.find_all_by_boat_type_id(@boat_post.boat_type_id), :id, :name, options ={:prompt => "Valitse merkki"}) %>
  </p>
   <p>
    <%= f.label :Laji %><br />
   <%=  collection_select(:boat_post, :boat_sub_type_id, BoatSubType.all, :id, :name , options ={:prompt => "Valitse laji"} ) %>
    </p>
   <div class="field">
    <%= f.label :Kuva%><br />
   <%= f.file_field :boat_cover_image%>
  </div>
<%= image_tag @boat_post.boat_cover_image.thumb('100x100').url if @boat_post.boat_cover_image_uid %>

  <div class="field">
    <%= f.label :Kuvan_nimi%><br />
    <%= f.text_field :boat_cover_image_name %>
  </div>
  <div class="field">
    <%= f.label :Malli%><br />
    <%= f.text_field :boat_model %>
  </div>
  <div class="field">
    <%= f.label :Vuosimalli %><br />
    <%= f.date_select :boat_year_model %>
  </div>
  <div class="field">
    <%= f.label :Hinta %><br />
    <%= f.text_field :boat_asking_price %>
  </div>
 <p>
    <%= f.label :Runkomateriaali %><br />
   <%=  collection_select(:boat_post, :boat_body_material_id, BoatBodyMaterial.all, :id, :name , options ={:prompt => "Valitse runkomateriaali"} ) %>
    </p>
  <p>
    <%= f.label "Väri" %><br />
   <%=  collection_select(:boat_post, :boat_color_id, BoatColor.all, :id, :name , options ={:prompt => "Valitse väri"} ) %>
    </p>
  <div class="field">
    <%= f.label :Pituus%><br />
    <%= f.text_field :boat_length %>
  </div>
  <div class="field">
    <%= f.label :Korkeus%><br />
    <%= f.text_field :boat_height %>
  </div>
  <div class="field">
    <%= f.label :Leveys%><br />
    <%= f.text_field :boat_width %>
  </div>
  <div class="field">
    <%= f.label :Paino %><br />
    <%= f.text_field :boat_weight %>
  </div>
  <div class="field">
    <%= f.label "Syväys" %><br />
    <%= f.text_field :boat_draught %>
  </div>
  <p>
    <%= f.label :Moottorin_merkki %><br />
   <%=  collection_select(:boat_post, :boat_engine_make_id, BoatEngineMake.all, :id, :name , options ={:prompt => "Valitse moottorin merkki"} ) %>
    </p>
  <div class="field">
    <%= f.label :Moottorin_vuosimalli %><br />
    <%= f.date_select :boat_engine_year_model %>
  </div>
  <p>
    <%= f.label :Polttoainetyyppi %><br />
   <%=  collection_select(:boat_post, :boat_engine_fuel_type_id, BoatEngineFuelType.all, :id, :name , options ={:prompt => "Valitse polttoainetyyppi"} ) %>
    </p>
  <div class="field">
    <%= f.label "Lisätiedot" %><br />
    <%= f.text_area :boat_note %>
  </div>
  <div class="field">
    <%= f.label "Omistajien_määrä" %><br />
    <%= f.text_field :boat_total_owner %>
  </div>
  <div class="field">
    <%= f.label :Varusteet %><br />
    <%= f.text_field :boat_storage_equipment %>
  </div>
<h2>
Omat tiedot
</h2> 
<h1>___________________________________________</h1>
   

  <div class="field">
    <%= f.label :Nimi %><br />
    <%= f.text_field :boat_user_name %>
  </div>
  <div class="field">
    <%= f.label :Puhelin %><br />
    <%= f.text_field :boat_user_phone %>
  </div>
  <div class="field">
    <%= f.label :Email %><br />
    <%= f.text_field :boat_user_email %>
  </div>
  <p>
    <%= f.label :Maakunta %><br />
   <%=  collection_select(:boat_post, :boat_domicile_type_id, BoatDomicileType.all, :id, :name , options ={:prompt => "Valitse maakunta"} ) %>
    </p>
  <p>
    <%= f.label :Paikkakunta %><br />
   <%= collection_select(:boat_post, :boat_town_type_id, BoatTownType.find_all_by_boat_domicile_type_id(@boat_post.boat_domicile_type_id), :id, :name, options ={:prompt => "Valitse paikkakunta"}) %>
  </p>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<script type="text/javascript">
    $(document).ready(function(){
        $("select#boat_post_boat_type_id").change(function(){
            var id_value_string = $(this).val();
            if (id_value_string == "") { 
                // if the id is empty remove all the sub_selection options from being selectable and do not do any ajax
                $("select#boat_post_boat_make_id option").remove();
                var row = "<option value=\"" + "" + "\">" + "" + "</option>";
                $(row).appendTo("select#boat_post_boat_make_id");
            }
            else {
                // Send the request and update sub category dropdown 
                $.ajax({
                    dataType: "json",
                    cache: false,
                    url: '/boat_make/for_boattypeid/' + id_value_string,
                    timeout: 2000,
                    error: function(XMLHttpRequest, errorTextStatus, error){
                        alert("Failed to submit : "+ errorTextStatus+" ;"+error);
                    },
                    success: function(data){                    
                        // Clear all options from sub category select 
                        $("select#boat_post_boat_make_id option").remove();
                        //put in a empty default line
                        var row = "<option value=\"" + "" + "\">" + "" + "</option>";
                        $(row).appendTo("select#boat_post_boat_make_id");                        
                        // Fill sub category select 
                        $.each(data, function(i, j){
                            row = "<option value=\"" + j.sub_section.id + "\">" + j.sub_section.name + "</option>";   
                            $(row).appendTo("select#boat_post_boat_make_id");                     
                        });             
                     }
                });
            };
                });
    });
</script>

app/views/boat_posts/edit.html.erb
<h1>Editing boat_post</h1>

<%= render 'form' %>

<%= link_to 'Show', @boat_post %> |
<%= link_to 'Back', boat_posts_path %>

app/views/boat_posts/index.html.erb
<h1>30 viimeisintä</h1>
<!-- projects/index.rhtml -->
<% form_tag boat_posts_path, :method => 'get' do %>
  



<% end %>


<table>
  <tr>
    <th>Merkki</th>
    <th></th>
    <th>Malli</th>
    <th>Vuosimalli</th>
    <th>Hinta</th>
    <th>Moottori</th>
    <th>Myyjä</th>
    <th>Puhelin</th>
    <th>Paikkakunta</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @boat_posts.each do |boat_post| %>
  <tr>
    <td><%= boat_post.boat_make.name %></td>
    <td><%= boat_post.boat_cover_image.url %></td>
    <td><%= boat_post.boat_model %></td>
    <td><%= boat_post.boat_year_model %></td>
    <td><%= boat_post.boat_asking_price %></td>
    <td><%= boat_post.boat_engine_make_id %></td>
    <td><%= boat_post.boat_user_name %></td>
    <td><%= boat_post.boat_user_phone %></td>
    <td><%= boat_post.boat_town_type.name %></td>
    <td><%= link_to 'Show', boat_post %></td>
    <td><%= link_to 'Edit', edit_boat_post_path(boat_post) %></td>
    <td><%= link_to 'Destroy', boat_post, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Jätä ilmoitus', new_boat_post_path %>

app/views/boat_posts/new.html.erb
<h1>Veneen tiedot</h1>
<h1>___________________________________________</h1>
<%= render 'form' %>

<%= link_to 'Back', boat_posts_path %>

app/views/boat_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Boat type:</b>
  <%= @boat_post.boat_type.name %>
</p>

<p>
  <b>Boat make:</b>
  <%= @boat_post.boat_make.name %>
</p>

<p>
  <b>Boat sub type:</b>
  <%= @boat_post.boat_sub_type.name %>
</p>

<p>
  <b>Boat cover image uid:</b>
  <%= image_tag @boat_post.boat_cover_image.url %>
  <%= image_tag @boat_post.boat_cover_image.thumb('400x200#').url %>
  <%= image_tag @boat_post.boat_cover_image.jpg.url %>
</p>

<p>
  <b>Boat cover image name:</b>
  <%= @boat_post.boat_cover_image_name %>
</p>

<p>
  <b>Boat model:</b>
  <%= @boat_post.boat_model %>
</p>

<p>
  <b>Boat year model:</b>
  <%= @boat_post.boat_year_model %>
</p>

<p>
  <b>Boat asking price:</b>
  <%= @boat_post.boat_asking_price %>
</p>

<p>
  <b>Boat body material:</b>
  <%= @boat_post.boat_body_material.name %>
</p>

<p>
  <b>Boat color:</b>
  <%= @boat_post.boat_color.name %>
</p>

<p>
  <b>Boat length:</b>
  <%= @boat_post.boat_length %>
</p>

<p>
  <b>Boat height:</b>
  <%= @boat_post.boat_height %>
</p>

<p>
  <b>Boat width:</b>
  <%= @boat_post.boat_width %>
</p>

<p>
  <b>Boat weight:</b>
  <%= @boat_post.boat_weight %>
</p>

<p>
  <b>Boat draught:</b>
  <%= @boat_post.boat_draught %>
</p>

<p>
  <b>Boat engine make:</b>
  <%= @boat_post.boat_engine_make.name %>
</p>

<p>
  <b>Boat engine year model:</b>
  <%= @boat_post.boat_engine_year_model %>
</p>

<p>
  <b>Boat engine fuel type:</b>
  <%= @boat_post.boat_engine_fuel_type.name %>
</p>

<p>
  <b>Boat note:</b>
  <%= @boat_post.boat_note %>
</p>

<p>
  <b>Boat total owner:</b>
  <%= @boat_post.boat_total_owner %>
</p>

<p>
  <b>Boat storage equipment:</b>
  <%= @boat_post.boat_storage_equipment %>
</p>

<p>
  <b>Boat user name:</b>
  <%= @boat_post.boat_user_name %>
</p>

<p>
  <b>Boat user phone:</b>
  <%= @boat_post.boat_user_phone %>
</p>

<p>
  <b>Boat user email:</b>
  <%= @boat_post.boat_user_email %>
</p>

<p>
  <b>Boat domicile type:</b>
  <%= @boat_post.boat_domicile_type.name %>
</p>

<p>
  <b>Boat town type:</b>
  <%= @boat_post.boat_town_type.name %>
</p>


<%= link_to 'Edit', edit_boat_post_path(@boat_post) %> |
<%= link_to 'Back', boat_posts_path %>